workflows:
  angular_build:
    name: Angular Build Workflow
    environment:
      groups:
        - angular_env_variables  # A group to manage your environment variables
      vars:
        NODE_ENV: development  # Example variable
    scripts:
      - name: Install dependencies with --force
        script: npm install --force
      - name: Set environment variables
        script: |
          echo "Setting up environment variables"
          export API_URL="http://example.com/api"
      - name: Build Angular app
        script: npm run build -- --configuration production
    artifacts:
      - dist/**
