workflows:
  ios-build:
    name: iOS Build Workflow
    environment:
      groups:
        - default
    scripts:
      - name: Install dependencies
        script: |
          npm install --force
      - name: Build Ionic App
        script: |
          ionic build --prod
      - name: Prepare Capacitor for iOS
        script: |
          ionic cap add ios
          ionic cap sync ios
      - name: Set Signing Info
        script: |
          sed -i '' "s/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = YOUR_TEAM_ID;/g" ios/App/App.xcodeproj/project.pbxproj
      - name: Build .ipa file
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -archivePath $PWD/build/App.xcarchive archive
          xcodebuild -exportArchive -archivePath $PWD/build/App.xcarchive -exportPath $PWD/build -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/*.ipa
