scripts:
  - name: Build unsigned IPA
    script: |
      cd ios
      xcodebuild -workspace App.xcworkspace \
                 -scheme App \
                 -configuration Release \
                 -sdk iphoneos \
                 -archivePath $PWD/build/App.xcarchive archive \
                 CODE_SIGN_IDENTITY="" \
                 CODE_SIGNING_REQUIRED=NO \
                 CODE_SIGN_ENTITLEMENTS="" \
                 CODE_SIGNING_ALLOWED=NO
      xcodebuild -exportArchive \
                 -archivePath $PWD/build/App.xcarchive \
                 -exportPath $PWD/build/ \
                 -exportOptionsPlist ExportOptions.plist \
                 CODE_SIGN_IDENTITY="" \
                 CODE_SIGNING_REQUIRED=NO \
                 CODE_SIGN_ENTITLEMENTS="" \
                 CODE_SIGNING_ALLOWED=NO
